config/routes.rb
Groceryminder::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  
  get "login" => "sessions#new", :as => "login"
  
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "lists#index"
  
  resources :purchases

  resources :groceries

  resources :lists

  resources :users
  
  resources :sessions

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :user
  has_many :groceries
  
  attr_accessible :list_name
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_filter :require_login
  
  # GET /lists
  # GET /lists.json
  def index
    @lists = List.where(:user_id => current_user.id)
    @list = List.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])
    
    @groceries = @list.groceries
    @grocery = Grocery.new
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @list }
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, :notice => 'List was successfully created.' }
        format.json { render :json => @list, :status => :created, :location => @list }
      else
        format.html { render :action => "new" }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])
    @list.user_id = current_user.id

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, :notice => 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @list.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
  
  # GET /lists/new
  # GET /lists/new.json
  # def new
  #     @list = List.new
  # 
  #     respond_to do |format|
  #       format.html # new.html.erb
  #       format.json { render :json => @list }
  #     end
  #   end

  # GET /lists/1/edit
  # def edit
  #     @list = List.find(params[:id])
  #   end
  
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_form.html.erb
<% 	
if defined? list_item
	list = list_item
else
	list = @list
end	
%>

<%= form_for(list) do |f| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :list_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lists/index.html.erb
<h1>Lists</h1>

<div class="all-user-lists">
<% @lists.each do |list| %>
<div class="user-list clearfix">
	<div class="user-list-name" id="list-name-<%= list.id %>">
    	<%= link_to list.list_name, list %>
		<%= list.updated_at %>
	</div>
	<div class="edit-list-form clearfix" id="list-form-<%= list.id %>">
		<%= render :partial => 'form', :locals => { :list_item => list } %>
	</div>
	<div class="user-list-options">
		<a href="javascript:void(0);" class="edit-list-button" id="edit-list-<%= list.id %>">Edit</a>
    	<%= link_to 'Destroy', list, :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>
<% end %>
</div>

<a href="javascript:void(0);" class="new-list-button">New List</a>

<div class="new-list-form">
	<%= render 'form' %>
</div>

app/views/lists/show.html.erb
<div class="user-list clearfix">
	<div class="user-list-name" id="list-name-<%= @list.id %>">
  		<%= @list.list_name %>
	</div>
	<div class="edit-list-form clearfix" id="list-form-<%= @list.id %>">
		<%= render 'form' %>
	</div>
	<div class="user-list-options">
		<a href="javascript:void(0);" class="edit-list-button" id="edit-list-<%= @list.id %>">Edit</a>
    	<%= link_to 'Destroy', @list, :confirm => 'Are you sure?', :method => :delete %>
	</div>
</div>

<ul class="grocery-messages">
</ul>

<div class="grocery-items">
<% @groceries.order('created_at DESC').each do |grocery| %>
  <%= render :partial => 'groceries/grocery-inline', :locals => { :grocery_item => grocery } %>
<% end %>
</div>

<a href="javascript:void(0);" class="new-grocery-button">New Grocery Item</a>

<div class="new-grocery-form">
	<%= render :partial => 'groceries/form', :locals => { :the_list_id => @list.id } %>
</div>

<p>
	<%= link_to 'Back', lists_path %>
</p>