config/routes.rb
Groceryminder::Application.routes.draw do
  
  get "logout" => "sessions#destroy", :as => "logout"
  
  get "login" => "sessions#new", :as => "login"
  
  get "sign_up" => "users#new", :as => "sign_up"

  root :to => "lists#index"
  
  resources :purchases

  resources :groceries

  resources :lists

  resources :users
  
  resources :sessions

end

app/models/grocery.rb
class Grocery < ActiveRecord::Base
  belongs_to :list
  has_many :purchases
  
  attr_accessible :grocery_name, :unit_increment, :unit, :upc_code, :current_amount, :unit_of_time_estimated
  
  attr_accessor :number_of_days
  
  validates_presence_of :list_id
  validates_presence_of :grocery_name
  validates_presence_of :unit_increment
  validates_presence_of :unit
  # validates_presence_of :number_of_days
  validates_presence_of :unit_of_time_estimated
  
end

app/controllers/groceries_controller.rb
class GroceriesController < ApplicationController
  
  respond_to :html, :js
  
  before_filter :require_login
  # before_filter :get_list_id, :only => [:create, :update]
  
  # GET /groceries
  # GET /groceries.json
  def index
    @groceries = Grocery.all
        
    respond_with(@groceries)
  end
  
  # GET /groceries/1
  # GET /groceries/1.json
  def show
    @grocery = Grocery.find(params[:id])
    
    respond_with(@grocery)
    # respond_to do |format|
    #   format.html # show.html.erb
    #   format.json { render :json => @grocery }
    # end
  end

  # POST /groceries
  # POST /groceries.json
  def create
    @list = List.find(params[:grocery][:list_id])
    @grocery = Grocery.new(params[:grocery].slice(:grocery_name, :unit_increment, :unit, :current_amount, :unit_of_time_estimated))
    @grocery.list_id = @list.id
    # @grocery.use_per_day_estimate = calc_use_per_day(params[:grocery][:unit_increment], params[:grocery][:number_of_days], params[:grocery][:unit_of_time_estimated])
    
    # if @grocery.save
    #       flash[:notice] = 'Grocery was successfully created.'
    #     else
    #       flash[:notice] = 'Error creating grocery.'
    #     end
    @grocery.save
    respond_with(@grocery)
  end

  # PUT /groceries/1
  # PUT /groceries/1.json
  def update
    @grocery = Grocery.find(params[:id])

    # respond_to do |format|
      if @grocery.update_attributes(params[:grocery])
        flash[:notice] = 'Grocery was successfully updated.'
        # format.html { redirect_to @grocery, :notice => 'Grocery was successfully updated.' }
        # format.json { head :no_content }
      else
        flash[:notice] = 'Error updating grocery.'
        # format.html { render :action => "edit" }
        # format.json { render :json => @grocery.errors, :status => :unprocessable_entity }
      end
      respond_with(@grocery)
    # end
  end

  # DELETE /groceries/1
  # DELETE /groceries/1.json
  def destroy
    @grocery = Grocery.find(params[:id])
    @grocery.destroy
    
    redirect_to groceries_url
    # respond_to do |format|
    #   format.html { redirect_to groceries_url }
    #   format.json { head :no_content }
    # end
  end
  
  protected    
    def get_list_id
      @list = current_user.lists.find(params[:id])
    end
    
  protected    
    def calc_use_per_day(total_amount, num_days, unit_of_time)
      total_amount.to_i
      num_days.to_i
      unit_of_time.to_i
      logger.debug(total_amount)
      logger.debug(num_days)
      logger.debug(unit_of_time)
      total_time = num_days * unit_of_time
      use_per_day = total_amount / total_time
      use_per_day
    end
end

app/helpers/groceries_helper.rb
module GroceriesHelper
end

app/views/groceries/_form-update-amount.html.erb
<% 	
if defined? grocery_item
	grocery = grocery_item
else
	grocery = @grocery
end	
%>

<%= form_for(grocery) do |f| %>
  <% if grocery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

      <ul>
      <% grocery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
		You are currently <%= f.number_field :current_amount, :placeholder => "50%", :step => "10", :min => "0", :max => "100" %>
  	</div>
	<div class="field">
		 stocked on <%= grocery.grocery_name %>
	</div>
  	<div class="actions">
    	<%= f.submit %>
  	</div>
<% end %>

app/views/groceries/_form.html.erb
<% 	
if defined? grocery_item
	grocery = grocery_item
else
	grocery = @grocery
end	
%>

<%= form_for(grocery, :remote => true, :html => { :id => 'create_grocery_form' }) do |f| %>
<div class="validation-error"></div>
  <% if grocery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(grocery.errors.count, "error") %> prohibited this grocery from being saved:</h2>

      <ul>
      <% grocery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div>
		<div class="field">
	    	You use <%= f.number_field :unit_increment, :placeholder => "1.0", :step => "0.1", :min => "0", :max => "9999" %>
		</div>
		<div class="field">
			<% grouped_options = [
					['Generic Measurements', [
						['Bag(s)', 'bag'],
						['Bar(s)', 'bar'],
						['Bottle(s)', 'bottle'],
						['Box(es)', 'box'],
						['Can(s)', 'can'],
						['Dozen', 'dozen'],
						['Individual', 'individual'],
						['Jar(s)', 'jar'],
						['Package(s)', 'package'],
					]],
					['Volume Measurements', [
						['Gallon(s)', 'gallon'], 
						['Liter(s)', 'liter'], 
						['Milliliter(s)', 'milliliter'], 
						['Pint(s)', 'pint'],
						['Quart(s)', 'quart']
					]],
					['Weight Measurements', [
						['Ounce(s)', 'ounce'],  
						['Pound(s)', 'pound']
					]],
				] %>
		    <%= select_tag "grocery[unit]", grouped_options_for_select(grouped_options, 'gallon') %>
		</div>
	  	<div class="field">
	    	of <%= f.text_field :grocery_name, :placeholder => "2% Milk", :size => "20" %>
	  	</div>
		<div class="field">
	    	every <%= f.number_field :number_of_days, :placeholder => "4", :step => "1", :min => "0", :max => "9999" %>
	  	</div>
	  	<div class="field">
	    	<%= f.select :unit_of_time_estimated, [['Day(s)', 1], ['Week(s)', 7], ['Month(s)', 30]] %>
	  	</div>
	</div>
	<div>
		<div class="field">
    		You are currently <%= f.number_field :current_amount, :placeholder => "50%", :step => "10", :min => "0", :max => "100" %> % stocked
  		</div>
	</div>
  	<div class="actions">
		<%= f.hidden_field :list_id, :value => @list.id %>
    	<%= f.submit 'Create Grocery', :class => 'create_grocery' %>
  	</div>
<% end %>

app/views/groceries/_grocery-inline.html.erb
<% 	
if defined? grocery_item
	grocery = grocery_item
else
	grocery = @grocery
end	
%>

<div class="grocery-item">
  <span><%= grocery.grocery_name %></span>
  <span><%= grocery.unit_increment %></span>
  <span><%= grocery.unit %></span>
  <span><%= grocery.current_amount %></span>
  <span><%= grocery.use_per_day_estimate %></span>
  <span><%= link_to 'Show', grocery %></span>
  <span><%= link_to 'Edit', edit_grocery_path(grocery) %></span>
  <span><%= link_to 'Destroy', grocery, :confirm => 'Are you sure?', :method => :delete %></span>
</div>

app/views/groceries/create.js.erb
// Create a list of errors
var messageContainer = $('.grocery-messages');
messageContainer.html('');

<% if @grocery.errors.any? %>

  	<% @grocery.errors.full_messages.each do |error| %>
  		messageContainer.append('<li class="error"><%= escape_javascript(error) %></li>');
  	<% end %>

<% else %>
	
	messageContainer.append('<li class="success">Grocery successfully created</li>');
  	// Add the new comment to the beginning of the #comment-container division
  	// $(".grocery-items").append('<%= j(render(:partial => "grocery-inline", :object => @grocery))%>').fadeIn(1000);
	$('<%= j(render(:partial => "grocery-inline", :object => @grocery))%>').hide().prependTo('.grocery-items').fadeIn('3000');

<% end %>

app/views/groceries/index.html.erb
<h1>Listing groceries</h1>

<table>
  <tr>
    <th>List</th>
    <th>Grocery name</th>
    <th>Increment</th>
    <th>Unit</th>
    <th>Upc code</th>
    <th>Current amount</th>
    <th>Use per day</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @groceries.each do |grocery| %>
  <tr>
    <td><%= grocery.list.list_name %></td>
    <td><%= grocery.grocery_name %></td>
    <td><%= grocery.unit_increment %></td>
    <td><%= grocery.unit %></td>
    <td><%= grocery.upc_code %></td>
    <td><%= grocery.current_amount %></td>
    <td><%= grocery.use_per_day_estimate %></td>
    <td><%= link_to 'Show', grocery %></td>
    <td><%= link_to 'Edit', edit_grocery_path(grocery) %></td>
    <td><%= link_to 'Destroy', grocery, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Grocery', new_grocery_path %>

app/views/groceries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Grocery name:</b>
  <%= @grocery.grocery_name %>
</p>

<p>
  <b>Increment:</b>
  <%= @grocery.unit_increment %>
</p>

<p>
  <b>Unit:</b>
  <%= @grocery.unit %>
</p>

<p>
  <b>Current amount:</b>
  <%= @grocery.current_amount %>
</p>

<p>
  <b>Use per day:</b>
  <%= @grocery.use_per_day_estimate %>
</p>